$axure.loadCurrentPage({
  "url":"新页面_3.html",
  "generationDate":new Date(1490338075854.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1126cd18a45c429a89cbd28aa7c99eb8",
    "type":"Axure:Page",
    "name":"新页面 3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF000000},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a994909220a477c8b24a9f24697fc90",
          "label":"kuang1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":195,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"21"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7812eb5b2c894b4da67ecfca8da44c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":195,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"21"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_3/kuang1_u0.png"}},
{
          "id":"03107128753043a981af80dbcf1a30b5",
          "label":"kuang2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":250,
              "y":75},
            "size":{
              "width":278,
              "height":430},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"21"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e1d4658ff1e49bf8828c3ced5e2e71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":250,
                  "y":75},
                "size":{
                  "width":278,
                  "height":430},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"21"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_3/kuang2_u2.png"}},
{
          "id":"21a819f2f7bb47268ef457a6519336aa",
          "label":"kuang3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":584,
              "y":0},
            "size":{
              "width":376,
              "height":580},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"21"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd636258a6194fbcad7324a905b7e025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":584,
                  "y":0},
                "size":{
                  "width":376,
                  "height":580},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"21"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/kuang3_u440.png"}},
{
          "id":"4dc985c1e484448b99a35e6a001c7d36",
          "label":"kuang4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1014,
              "y":73},
            "size":{
              "width":277,
              "height":427},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"21"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b59a33682b401fa77b83c337cb8c1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1014,
                  "y":73},
                "size":{
                  "width":277,
                  "height":427},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"21"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/kuang4_u401.png"}},
{
          "id":"a099488dc62b41dab73eaae4713fa6a3",
          "label":"kuang5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1346,
              "y":137},
            "size":{
              "width":194,
              "height":299},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"21"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc79f46b01d4965835195754cef1ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1346,
                  "y":137},
                "size":{
                  "width":194,
                  "height":299},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"21"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_3/kuang5_u8.png"}},
{
          "id":"54d664d8acb84d01bfc485f67c1bc2c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":728,
              "y":12},
            "size":{
              "width":85,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb53dd81efff4ada861d45186fc50e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":728,
                  "y":12},
                "size":{
                  "width":85,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"诉讼财产保全"},
          "images":{
            "normal~":"images/首页/u417.png"}},
{
          "id":"7d5d7cfef2124d6ab2ffa545e29e80ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":86},
            "size":{
              "width":63,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9df81afd25d0472aadd3222e14e07ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":86},
                "size":{
                  "width":63,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"车险"},
          "images":{
            "normal~":"images/首页/u415.png"}},
{
          "id":"36790ed4380f4b75b0d228fb20053e66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":149},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c96540a382040ddab6b77f235a63bc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":149},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"雇主责任"},
          "images":{
            "normal~":"images/首页/u413.png"}},
{
          "id":"206119da0df944ea8ac3363b6901c256",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1126,
              "y":86},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"587677128b8a4a019f59ccdb9eb51877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1126,
                  "y":86},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"食品安全"},
          "images":{
            "normal~":"images/首页/u407.png"}},
{
          "id":"017e7f093e6b4b8abe54325b20d23a09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1420,
              "y":151},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2408db61e6b444a384c64b491cf526a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1420,
                  "y":151},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"儿童健康"},
          "images":{
            "normal~":"images/首页/u419.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a994909220a477c8b24a9f24697fc90":{
      "scriptId":"u0"},
    "7812eb5b2c894b4da67ecfca8da44c04":{
      "scriptId":"u1"},
    "03107128753043a981af80dbcf1a30b5":{
      "scriptId":"u2"},
    "5e1d4658ff1e49bf8828c3ced5e2e71d":{
      "scriptId":"u3"},
    "21a819f2f7bb47268ef457a6519336aa":{
      "scriptId":"u4"},
    "dd636258a6194fbcad7324a905b7e025":{
      "scriptId":"u5"},
    "4dc985c1e484448b99a35e6a001c7d36":{
      "scriptId":"u6"},
    "92b59a33682b401fa77b83c337cb8c1a":{
      "scriptId":"u7"},
    "a099488dc62b41dab73eaae4713fa6a3":{
      "scriptId":"u8"},
    "8bc79f46b01d4965835195754cef1ea2":{
      "scriptId":"u9"},
    "54d664d8acb84d01bfc485f67c1bc2c5":{
      "scriptId":"u10"},
    "fb53dd81efff4ada861d45186fc50e5f":{
      "scriptId":"u11"},
    "7d5d7cfef2124d6ab2ffa545e29e80ee":{
      "scriptId":"u12"},
    "9df81afd25d0472aadd3222e14e07ae9":{
      "scriptId":"u13"},
    "36790ed4380f4b75b0d228fb20053e66":{
      "scriptId":"u14"},
    "5c96540a382040ddab6b77f235a63bc1":{
      "scriptId":"u15"},
    "206119da0df944ea8ac3363b6901c256":{
      "scriptId":"u16"},
    "587677128b8a4a019f59ccdb9eb51877":{
      "scriptId":"u17"},
    "017e7f093e6b4b8abe54325b20d23a09":{
      "scriptId":"u18"},
    "2408db61e6b444a384c64b491cf526a0":{
      "scriptId":"u19"}}});