$axure.loadCurrentPage({
  "url":"新页面_1.html",
  "generationDate":new Date(1490338075560.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"607686c5fe3a43789027d67da9156f8e",
    "type":"Axure:Page",
    "name":"新页面 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0de185a4c7a744cc8b384892fcb3a7a1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-313,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"690ee3627c03414989ddffb1932603cf"},
{
          "id":"8777625986204a60bf1301ee9edc9c57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":56},
            "size":{
              "width":1040,
              "height":204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dac454226424e95825a8008f8824874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":56},
                "size":{
                  "width":1040,
                  "height":204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u72.png"}}]}},
  "masters":{
    "690ee3627c03414989ddffb1932603cf":{
      "packageId":"690ee3627c03414989ddffb1932603cf",
      "type":"Axure:Master",
      "name":"foot",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dd3847f49c4b43ada1d2d14aa1ce6fb2",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":64,
                "y":466},
              "size":{
                "width":1449,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF67CE04},
{
                    "color":0xFF67CE04},
{
                    "color":0xFF85FA57},
{
                    "color":0xFF6ED816},
{
                    "color":0xFF6ED816}]}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u265_line.png"}},
{
            "id":"2621dacc15014f729036026f44388b68",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":571},
              "size":{
                "width":97,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eaae52c76f434050b82348ca453aa58f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":571},
                  "size":{
                    "width":97,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0783857c5d074defb09200a97101fc22",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":0,
                "y":624},
              "size":{
                "width":81,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0620cb18b8924f0089f810b97a1e1fbb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":624},
                  "size":{
                    "width":81,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"caeed385e62f49428f3eba195162009e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":0,
                "y":660},
              "size":{
                "width":81,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"26c965e77c634cb3a6ef0b9127955622",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":660},
                  "size":{
                    "width":81,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fe191b9866e746bc9dddc0ccdc8006f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":0,
                "y":695},
              "size":{
                "width":101,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82bbae1b0490482abe7ed7b898061bef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":695},
                  "size":{
                    "width":101,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"381f4f311d354c08b8be6764efe495ad",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":202,
                "y":571},
              "size":{
                "width":97,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a3f8f9d7cf534096898f48c965396ac5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":202,
                    "y":571},
                  "size":{
                    "width":97,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a1ad359522fd41a58e671ddf6c355757",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":202,
                "y":624},
              "size":{
                "width":81,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ffda5bf6cd904c3890171a97a5b68192",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":202,
                    "y":624},
                  "size":{
                    "width":81,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fb9d0962c13b4a9bb78c89cee72b4316",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":202,
                "y":660},
              "size":{
                "width":81,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08f91d83d3c945b8b5933ee1e03f4b7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":202,
                    "y":660},
                  "size":{
                    "width":81,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8bb154735800424682ac0f6c7afb6262",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":202,
                "y":695},
              "size":{
                "width":61,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"70712554f5b5453b85663d746305583c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":202,
                    "y":695},
                  "size":{
                    "width":61,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"051c6c9a780e4dac8fdb9a89922ef572",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":202,
                "y":731},
              "size":{
                "width":123,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19609721583a41e7837e0784010eb073",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":202,
                    "y":731},
                  "size":{
                    "width":123,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"44d0a5c7ac02406e92078a02650bcfba",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":424,
                "y":571},
              "size":{
                "width":97,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e8e6a4420fa4127a24836c48c766415",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":571},
                  "size":{
                    "width":97,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23827dbbf00441d5833b515a98b41743",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":424,
                "y":624},
              "size":{
                "width":101,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"61dc3b7ca1ab4faebf661b5188aabfbc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":624},
                  "size":{
                    "width":101,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0a92f3b5f67744138bff7c0c7da87bc3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":536,
                "y":624},
              "size":{
                "width":177,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"827c5666b9a141428f5722807d2765bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":536,
                    "y":624},
                  "size":{
                    "width":177,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"12116661b1864ba5986c877a04a8f6cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":424,
                "y":697},
              "size":{
                "width":61,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d73a544f3606490787e753907a91a0ef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":697},
                  "size":{
                    "width":61,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2b29580771f646e2bd0f0996287c10ab",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":424,
                "y":745},
              "size":{
                "width":41,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e65abb43339c4e379f11ef134b587155",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":745},
                  "size":{
                    "width":41,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"moveWidget",
                        "description":"移动 xian 到 ([[this.x]],[[this.y+35]])",
                        "objectsToMoves":[{
                            "objectPath":["2a68b4cf21a84115a5ab75151c4049d7"],
                            "moveInfo":{
                              "moveType":"location",
                              "xValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.x]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"x"}]},
                              "yValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.y+35]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "computedType":"int",
                                      "sto":"propCall",
                                      "thisSTO":{
                                        "sto":"var",
                                        "name":"this"},
                                      "prop":"y"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":35}}]},
                              "options":{
}}}]},
{
                        "action":"setPanelState",
                        "description":"设置 dizhi to 状态1 淡入淡出 in 1000ms 显示隐藏",
                        "panelsToStates":[{
                            "panelPath":["63e9f31c6f7e43f9bfc82c408e15b8a9"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":1,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":true,
                              "options":{
                                "animateIn":{
                                  "easing":"fade",
                                  "duration":1000},
                                "compress":false}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a68b4cf21a84115a5ab75151c4049d7",
            "label":"xian",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":426,
                "y":778},
              "size":{
                "width":37,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF66FFCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/xian_u351_line.png"}},
{
            "id":"a4ed760d2fb1415a927eeb7ee3fd96a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":484,
                "y":745},
              "size":{
                "width":41,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67e1ac5003774f65baeedef1fc3c9ea4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":484,
                    "y":745},
                  "size":{
                    "width":41,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"moveWidget",
                        "description":"移动 xian 到 ([[this.x]],[[this.y+35]])",
                        "objectsToMoves":[{
                            "objectPath":["2a68b4cf21a84115a5ab75151c4049d7"],
                            "moveInfo":{
                              "moveType":"location",
                              "xValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.x]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"x"}]},
                              "yValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.y+35]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "computedType":"int",
                                      "sto":"propCall",
                                      "thisSTO":{
                                        "sto":"var",
                                        "name":"this"},
                                      "prop":"y"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":35}}]},
                              "options":{
}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a39038f2b6b47f887cbd333709ad857",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":546,
                "y":745},
              "size":{
                "width":41,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2ab406cd501a4bae8c5257b9c5ad54c5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":546,
                    "y":745},
                  "size":{
                    "width":41,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"moveWidget",
                        "description":"移动 xian 到 ([[this.x]],[[this.y+35]])",
                        "objectsToMoves":[{
                            "objectPath":["2a68b4cf21a84115a5ab75151c4049d7"],
                            "moveInfo":{
                              "moveType":"location",
                              "xValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.x]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"x"}]},
                              "yValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.y+35]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "computedType":"int",
                                      "sto":"propCall",
                                      "thisSTO":{
                                        "sto":"var",
                                        "name":"this"},
                                      "prop":"y"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":35}}]},
                              "options":{
}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9cb145da4ea949ff8a27ed4154bf7970",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":612,
                "y":745},
              "size":{
                "width":41,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4f9cff837104d7980a40b7a123d429a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":612,
                    "y":745},
                  "size":{
                    "width":41,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"moveWidget",
                        "description":"移动 xian 到 ([[this.x]],[[this.y+35]])",
                        "objectsToMoves":[{
                            "objectPath":["2a68b4cf21a84115a5ab75151c4049d7"],
                            "moveInfo":{
                              "moveType":"location",
                              "xValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.x]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"x"}]},
                              "yValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.y+35]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "computedType":"int",
                                      "sto":"propCall",
                                      "thisSTO":{
                                        "sto":"var",
                                        "name":"this"},
                                      "prop":"y"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":35}}]},
                              "options":{
}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d2993bf514d64c1d8d5e6b41a3c33a9c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":678,
                "y":745},
              "size":{
                "width":41,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f576f135df8140caaa804a2e3b9e83f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":678,
                    "y":745},
                  "size":{
                    "width":41,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"moveWidget",
                        "description":"移动 xian 到 ([[this.x]],[[this.y+35]])",
                        "objectsToMoves":[{
                            "objectPath":["2a68b4cf21a84115a5ab75151c4049d7"],
                            "moveInfo":{
                              "moveType":"location",
                              "xValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.x]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"x"}]},
                              "yValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.y+35]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "computedType":"int",
                                      "sto":"propCall",
                                      "thisSTO":{
                                        "sto":"var",
                                        "name":"this"},
                                      "prop":"y"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":35}}]},
                              "options":{
}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"61c7699b877640ccb756ad79899dceff",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":736,
                "y":745},
              "size":{
                "width":41,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05289b7197734ffaab7c7940a8f3b95b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":736,
                    "y":745},
                  "size":{
                    "width":41,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"moveWidget",
                        "description":"移动 xian 到 ([[this.x]],[[this.y+35]])",
                        "objectsToMoves":[{
                            "objectPath":["2a68b4cf21a84115a5ab75151c4049d7"],
                            "moveInfo":{
                              "moveType":"location",
                              "xValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.x]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"x"}]},
                              "yValue":{
                                "exprType":"stringLiteral",
                                "value":"[[this.y+35]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "computedType":"int",
                                      "sto":"propCall",
                                      "thisSTO":{
                                        "sto":"var",
                                        "name":"this"},
                                      "prop":"y"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":35}}]},
                              "options":{
}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"273ca1565f26472492e7bab3705eb72b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":878,
                "y":571},
              "size":{
                "width":97,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0758f25f72ca4bab96b98fb828bf8f15",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":878,
                    "y":571},
                  "size":{
                    "width":97,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1cf16a27126449a39ae8d14079306fe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":424,
                "y":660},
              "size":{
                "width":131,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"27ebc80d9cb74107aa8d613a47a832dd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":660},
                  "size":{
                    "width":131,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"42e5ecbaa630413fb0c6069b1cfd13e0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":878,
                "y":623},
              "size":{
                "width":145,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a23fb13d104c47d580a66dd5847f0832",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":878,
                    "y":623},
                  "size":{
                    "width":145,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u366.png"}},
{
            "id":"c8cc981c834f4498a77b97fe5d29a058",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"22px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF66FFCC,
                "opacity":1},
              "location":{
                "x":1416,
                "y":624},
              "size":{
                "width":135,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd7dcce1ce3248f69ec4287f784db81a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"22px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF66FFCC,
                    "opacity":1},
                  "location":{
                    "x":1416,
                    "y":624},
                  "size":{
                    "width":135,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cb81f8cc348641dd83a13e2940fb3f73",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1374,
                "y":670},
              "size":{
                "width":225,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"188a10bdcc5642c686fff7e0443e2909",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1374,
                    "y":670},
                  "size":{
                    "width":225,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"207c5d5164734739b19740881abccddd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":1338,
                "y":731},
              "size":{
                "width":290,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4fcd3feab95348858169ea11c5e73708",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":1338,
                    "y":731},
                  "size":{
                    "width":290,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9aa801ec057148b0a6533e6fb9283cdd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":318,
                "y":836},
              "size":{
                "width":988,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6875f3263f7a40c386604d21bc574ac6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":318,
                    "y":836},
                  "size":{
                    "width":988,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e8c749ed17384eaaba6c5515aaf18d3c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF00FFFF,
                "opacity":1},
              "location":{
                "x":786,
                "y":869},
              "size":{
                "width":52,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dedb7f4e9928490688c193d260981586",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF00FFFF,
                    "opacity":1},
                  "location":{
                    "x":786,
                    "y":869},
                  "size":{
                    "width":52,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://new.cnzz.com/v1/login.php?siteid=1256835151",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://new.cnzz.com/v1/login.php?siteid=1256835151",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"63e9f31c6f7e43f9bfc82c408e15b8a9",
            "label":"dizhi",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":313,
                "y":0},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "fixedHorizontal":"center",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"986578ba81604093815415a0d768c345",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"0b42ceef6ece4311a86783a3752bbab0",
                    "label":"",
                    "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "opacity":"0.8",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF333333},
                      "size":{
                        "width":1840,
                        "height":890},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF333333}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6b3c5d497b4c4d7ca381c3cac2b3e70c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "opacity":"0.8",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333},
                          "size":{
                            "width":1840,
                            "height":890},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF333333}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u383.png"}},
{
                    "id":"095fcaac7b3b4f0d8e68c5c7e3deda7a",
                    "label":"",
                    "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":319,
                        "y":222},
                      "size":{
                        "width":1203,
                        "height":445}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"eacfae35b5314c3e99e0a7ed52d037ba",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":319,
                            "y":222},
                          "size":{
                            "width":1203,
                            "height":445}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u385.png"}},
{
                    "id":"872bcff06c05436da917bcf50a6d5df8",
                    "label":"",
                    "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1699,
                        "y":40},
                      "size":{
                        "width":61,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"73661f049e384d92960ee8e94fd18c3d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1699,
                            "y":40},
                          "size":{
                            "width":61,
                            "height":60}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"隐藏 dizhi 淡入淡出 1000 ms",
                                "objectsToFades":[{
                                    "objectPath":["63e9f31c6f7e43f9bfc82c408e15b8a9"],
                                    "fadeInfo":{
                                      "fadeType":"hide",
                                      "options":{
                                        "easing":"fade",
                                        "duration":1000,
                                        "showType":"none"}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/首页/u387.png"}},
{
                    "id":"ef0a21447ca54a12b8730ccb01655a6f",
                    "label":"",
                    "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1615,
                        "y":414},
                      "size":{
                        "width":60,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9513f672781c4e2b84ab690aaa07a13b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1615,
                            "y":414},
                          "size":{
                            "width":60,
                            "height":60}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u136.png"}},
{
                    "id":"1be136e8d32f4f9ebe002dfd4b1db58a",
                    "label":"",
                    "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":165,
                        "y":414},
                      "size":{
                        "width":60,
                        "height":60},
                      "rotation":"180",
                      "textRotation":"180"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"850f86269ea1498498f66afac1b72fa7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"63e9f31c6f7e43f9bfc82c408e15b8a9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":165,
                            "y":414},
                          "size":{
                            "width":60,
                            "height":60},
                          "rotation":"180",
                          "textRotation":"180"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u136.png"}}]}]},
{
            "id":"cfab899f635f4a1194f6f8befd465a9c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1112,
                "y":571},
              "size":{
                "width":97,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7c835675d0943e193008cf09ff6a43b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1112,
                    "y":571},
                  "size":{
                    "width":97,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"36a0665459be47cb879deb7a445639f6",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "location":{
                "x":1112,
                "y":624},
              "size":{
                "width":181,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9c8f7844f3141d88ae2e95224109661",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "location":{
                    "x":1112,
                    "y":624},
                  "size":{
                    "width":181,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "0de185a4c7a744cc8b384892fcb3a7a1":{
      "scriptId":"u0",
      "dd3847f49c4b43ada1d2d14aa1ce6fb2":{
        "scriptId":"u1"},
      "2621dacc15014f729036026f44388b68":{
        "scriptId":"u2"},
      "eaae52c76f434050b82348ca453aa58f":{
        "scriptId":"u3"},
      "0783857c5d074defb09200a97101fc22":{
        "scriptId":"u4"},
      "0620cb18b8924f0089f810b97a1e1fbb":{
        "scriptId":"u5"},
      "caeed385e62f49428f3eba195162009e":{
        "scriptId":"u6"},
      "26c965e77c634cb3a6ef0b9127955622":{
        "scriptId":"u7"},
      "fe191b9866e746bc9dddc0ccdc8006f9":{
        "scriptId":"u8"},
      "82bbae1b0490482abe7ed7b898061bef":{
        "scriptId":"u9"},
      "381f4f311d354c08b8be6764efe495ad":{
        "scriptId":"u10"},
      "a3f8f9d7cf534096898f48c965396ac5":{
        "scriptId":"u11"},
      "a1ad359522fd41a58e671ddf6c355757":{
        "scriptId":"u12"},
      "ffda5bf6cd904c3890171a97a5b68192":{
        "scriptId":"u13"},
      "fb9d0962c13b4a9bb78c89cee72b4316":{
        "scriptId":"u14"},
      "08f91d83d3c945b8b5933ee1e03f4b7b":{
        "scriptId":"u15"},
      "8bb154735800424682ac0f6c7afb6262":{
        "scriptId":"u16"},
      "70712554f5b5453b85663d746305583c":{
        "scriptId":"u17"},
      "051c6c9a780e4dac8fdb9a89922ef572":{
        "scriptId":"u18"},
      "19609721583a41e7837e0784010eb073":{
        "scriptId":"u19"},
      "44d0a5c7ac02406e92078a02650bcfba":{
        "scriptId":"u20"},
      "1e8e6a4420fa4127a24836c48c766415":{
        "scriptId":"u21"},
      "23827dbbf00441d5833b515a98b41743":{
        "scriptId":"u22"},
      "61dc3b7ca1ab4faebf661b5188aabfbc":{
        "scriptId":"u23"},
      "0a92f3b5f67744138bff7c0c7da87bc3":{
        "scriptId":"u24"},
      "827c5666b9a141428f5722807d2765bb":{
        "scriptId":"u25"},
      "12116661b1864ba5986c877a04a8f6cd":{
        "scriptId":"u26"},
      "d73a544f3606490787e753907a91a0ef":{
        "scriptId":"u27"},
      "2b29580771f646e2bd0f0996287c10ab":{
        "scriptId":"u28"},
      "e65abb43339c4e379f11ef134b587155":{
        "scriptId":"u29"},
      "2a68b4cf21a84115a5ab75151c4049d7":{
        "scriptId":"u30"},
      "a4ed760d2fb1415a927eeb7ee3fd96a4":{
        "scriptId":"u31"},
      "67e1ac5003774f65baeedef1fc3c9ea4":{
        "scriptId":"u32"},
      "2a39038f2b6b47f887cbd333709ad857":{
        "scriptId":"u33"},
      "2ab406cd501a4bae8c5257b9c5ad54c5":{
        "scriptId":"u34"},
      "9cb145da4ea949ff8a27ed4154bf7970":{
        "scriptId":"u35"},
      "d4f9cff837104d7980a40b7a123d429a":{
        "scriptId":"u36"},
      "d2993bf514d64c1d8d5e6b41a3c33a9c":{
        "scriptId":"u37"},
      "f576f135df8140caaa804a2e3b9e83f9":{
        "scriptId":"u38"},
      "61c7699b877640ccb756ad79899dceff":{
        "scriptId":"u39"},
      "05289b7197734ffaab7c7940a8f3b95b":{
        "scriptId":"u40"},
      "273ca1565f26472492e7bab3705eb72b":{
        "scriptId":"u41"},
      "0758f25f72ca4bab96b98fb828bf8f15":{
        "scriptId":"u42"},
      "1cf16a27126449a39ae8d14079306fe1":{
        "scriptId":"u43"},
      "27ebc80d9cb74107aa8d613a47a832dd":{
        "scriptId":"u44"},
      "42e5ecbaa630413fb0c6069b1cfd13e0":{
        "scriptId":"u45"},
      "a23fb13d104c47d580a66dd5847f0832":{
        "scriptId":"u46"},
      "c8cc981c834f4498a77b97fe5d29a058":{
        "scriptId":"u47"},
      "cd7dcce1ce3248f69ec4287f784db81a":{
        "scriptId":"u48"},
      "cb81f8cc348641dd83a13e2940fb3f73":{
        "scriptId":"u49"},
      "188a10bdcc5642c686fff7e0443e2909":{
        "scriptId":"u50"},
      "207c5d5164734739b19740881abccddd":{
        "scriptId":"u51"},
      "4fcd3feab95348858169ea11c5e73708":{
        "scriptId":"u52"},
      "9aa801ec057148b0a6533e6fb9283cdd":{
        "scriptId":"u53"},
      "6875f3263f7a40c386604d21bc574ac6":{
        "scriptId":"u54"},
      "e8c749ed17384eaaba6c5515aaf18d3c":{
        "scriptId":"u55"},
      "dedb7f4e9928490688c193d260981586":{
        "scriptId":"u56"},
      "63e9f31c6f7e43f9bfc82c408e15b8a9":{
        "scriptId":"u57"},
      "0b42ceef6ece4311a86783a3752bbab0":{
        "scriptId":"u58"},
      "6b3c5d497b4c4d7ca381c3cac2b3e70c":{
        "scriptId":"u59"},
      "095fcaac7b3b4f0d8e68c5c7e3deda7a":{
        "scriptId":"u60"},
      "eacfae35b5314c3e99e0a7ed52d037ba":{
        "scriptId":"u61"},
      "872bcff06c05436da917bcf50a6d5df8":{
        "scriptId":"u62"},
      "73661f049e384d92960ee8e94fd18c3d":{
        "scriptId":"u63"},
      "ef0a21447ca54a12b8730ccb01655a6f":{
        "scriptId":"u64"},
      "9513f672781c4e2b84ab690aaa07a13b":{
        "scriptId":"u65"},
      "1be136e8d32f4f9ebe002dfd4b1db58a":{
        "scriptId":"u66"},
      "850f86269ea1498498f66afac1b72fa7":{
        "scriptId":"u67"},
      "cfab899f635f4a1194f6f8befd465a9c":{
        "scriptId":"u68"},
      "e7c835675d0943e193008cf09ff6a43b":{
        "scriptId":"u69"},
      "36a0665459be47cb879deb7a445639f6":{
        "scriptId":"u70"},
      "d9c8f7844f3141d88ae2e95224109661":{
        "scriptId":"u71"}},
    "8777625986204a60bf1301ee9edc9c57":{
      "scriptId":"u72"},
    "2dac454226424e95825a8008f8824874":{
      "scriptId":"u73"}}});