$axure.loadCurrentPage({
  "url":"核心产品.html",
  "generationDate":new Date(1490338071712.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"57d0f9f38a274c4d82656d8a1d11308e",
    "type":"Axure:Page",
    "name":"核心产品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8bc291f6328b4f2090509a23fcda9f00",
          "label":"1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF66,
                  "opacity":1}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF6699FF},
{
                  "color":0xFF789BC3},
{
                  "color":0xFF789BC3}]},
            "size":{
              "width":1840,
              "height":3880},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9AB4D5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b77eb4906ca49468cdbaec0a8004f6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF66,
                      "opacity":1}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF6699FF},
{
                      "color":0xFF789BC3},
{
                      "color":0xFF789BC3}]},
                "size":{
                  "width":1840,
                  "height":3880},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9AB4D5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/1_u0.png",
            "selected~":"images/核心产品/1_u0.png"}},
{
          "id":"05eaeeb719c44572802074c11650025b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":25},
            "size":{
              "width":60,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f38c54b1ff48a8bc803c27840f2398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":25},
                "size":{
                  "width":60,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u59.png"}},
{
          "id":"9285a54b817a4c398d92192e10d795c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":170,
              "y":36},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c32c39e51cb443a8ce9bc6ba7f2207b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":36},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"全心全意，联心共赢！PS：注意不要用方正字体"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe8247f2731447f3b718db486cfb9ba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":775,
              "y":42},
            "size":{
              "width":46,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4efb47d44c0448c8b9a454ffecc366a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":775,
                  "y":42},
                "size":{
                  "width":46,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"192d4d785be54e34b41beec12517bf6b",
          "label":"erjicaidan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":842.5,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c420e3634f1643b6a9c7a86166f3754e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ca6ab24f9e9841d18bead05e5d63bad2",
                  "label":"erjicaidan",
                  "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC},
                    "size":{
                      "width":160,
                      "height":290},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22259df03950422c938ca4b6dd40c8b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC},
                        "size":{
                          "width":160,
                          "height":290},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/erjicaidan_u9.png"}},
{
                  "id":"9cf333cafbd444739b67a2db58fc71ba",
                  "label":"",
                  "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":121},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4b55664ede843e6936680a920e58756",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":121},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"9432ffb6a22e45b8b95865631dccb203",
                  "label":"",
                  "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":153},
                    "size":{
                      "width":38,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56a65db34ff342ccb8ae27e530c8ab61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":153},
                        "size":{
                          "width":38,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ca6ab24f9e9841d18bead05e5d63bad2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"560914d81a7a4543af2dfdd43db22b45",
                  "label":"",
                  "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":185},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e769545c7d0943089fcdf9eecc71e966",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":185},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ca6ab24f9e9841d18bead05e5d63bad2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"72b5d5ac28f2453c8f39ebcae83a1e7a",
                  "label":"",
                  "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":217},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"255cd50527bc485db2a6cd35a9fa74e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":217},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ca6ab24f9e9841d18bead05e5d63bad2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"afc074ad432d4878b08be5192cc4ab7d",
                  "label":"",
                  "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":249},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45d59b0d273342a1bc9f7e86b520e762",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"192d4d785be54e34b41beec12517bf6b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":249},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ca6ab24f9e9841d18bead05e5d63bad2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5df5b1d8f0f74f2fa85bae03bc1b7a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":877,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c49aaff9e6466aa78db311d0659e5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":877,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["192d4d785be54e34b41beec12517bf6b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["192d4d785be54e34b41beec12517bf6b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"206e6e34037548dd816da6672708601a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1023,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7897f867b0be4b16a2662bed64233e1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1023,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务咨询",
                      "target":{
                        "targetType":"page",
                        "url":"服务咨询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7af1d4d7676145cbae9de891e10f2c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1170,
              "y":42},
            "size":{
              "width":113,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4ed9846ed654f0aabb3613ca5c6cac4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1170,
                  "y":42},
                "size":{
                  "width":113,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7011623e291a4b258a101eacb4caf49e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1339,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f53a50524d98464f97f8091f3cf7d91b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1339,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"d1c8e25d183f467ca3adff2c266eb268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1485,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a432309935014f4cb9457deb4f342830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1485,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"af45aa9f3d194971a35798238c5355b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF66,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1632,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3538d8af73de47a2bb72b8fcbd1ea293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF66,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1632,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b8c23b3ac09d4c98a104dd40db925f51",
          "label":"biankuang",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517934cdff8744b789911507b0ec86f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":1840,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/biankuang_u33.png"}},
{
          "id":"fe6ae50aabd940baa67222566f88880d",
          "label":"fengexian",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 2 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["fe6ae50aabd940baa67222566f88880d"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]},
            "onResize":{
              "description":"OnResize",
              "cases":[{
                  "description":"用例 2<br> (If &quot;[[this.width]]&quot; ≥ &quot;1800&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">=",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1800",
                      "stos":[]}},
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 1840 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["fe6ae50aabd940baa67222566f88880d"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1840",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]},
{
                  "description":"用例 1<br> (Else If &quot;[[this.width]]&quot; &lt; &quot;1840&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1840",
                      "stos":[]}},
                  "actions":[{
                      "action":"wait",
                      "description":"等待100毫秒",
                      "waitTime":100},
{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to [[this.width+80]] x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["fe6ae50aabd940baa67222566f88880d"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"[[this.width+80]]",
                              "localVariables":{
},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"binOp",
                                  "op":"+",
                                  "leftSTO":{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"width"},
                                  "rightSTO":{
                                    "computedType":"int",
                                    "sto":"literal",
                                    "value":80}}]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"390af92571d64b06bf4bc81bdef8510d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dfb3610fb7e24943b90d37dba2250af9",
                  "label":"",
                  "parentDynamicPanel":"fe6ae50aabd940baa67222566f88880d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF3E7865},
{
                          "color":0xFF3E7865},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]},
                    "size":{
                      "width":1840,
                      "height":3},
                    "borderFill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF27AB7E},
{
                          "color":0xFF27AB7E},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"720d3198a8f24d5b9723db6e9a0f75e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fe6ae50aabd940baa67222566f88880d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF3E7865},
{
                              "color":0xFF3E7865},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]},
                        "size":{
                          "width":1840,
                          "height":3},
                        "borderFill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF27AB7E},
{
                              "color":0xFF27AB7E},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u80.png"}},
{
                  "id":"164f1bab0dd84c3cb2c41683ef21d099",
                  "label":"",
                  "parentDynamicPanel":"fe6ae50aabd940baa67222566f88880d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-448,
                      "y":146},
                    "size":{
                      "width":2298,
                      "height":294}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"112e1778f3b64ce8b3ebe1eb84182e35",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fe6ae50aabd940baa67222566f88880d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-448,
                          "y":146},
                        "size":{
                          "width":2298,
                          "height":294}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/u38.png"}}]}]},
{
          "id":"e6832a59e2ce4332ad76eab66c1c33f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":46},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8298d83b51f9431587d6fe0f3bf26c48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":46},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8bc291f6328b4f2090509a23fcda9f00":{
      "scriptId":"u0"},
    "2b77eb4906ca49468cdbaec0a8004f6c":{
      "scriptId":"u1"},
    "05eaeeb719c44572802074c11650025b":{
      "scriptId":"u2"},
    "c9f38c54b1ff48a8bc803c27840f2398":{
      "scriptId":"u3"},
    "9285a54b817a4c398d92192e10d795c5":{
      "scriptId":"u4"},
    "4c32c39e51cb443a8ce9bc6ba7f2207b":{
      "scriptId":"u5"},
    "fe8247f2731447f3b718db486cfb9ba8":{
      "scriptId":"u6"},
    "f4efb47d44c0448c8b9a454ffecc366a":{
      "scriptId":"u7"},
    "192d4d785be54e34b41beec12517bf6b":{
      "scriptId":"u8"},
    "ca6ab24f9e9841d18bead05e5d63bad2":{
      "scriptId":"u9"},
    "22259df03950422c938ca4b6dd40c8b5":{
      "scriptId":"u10"},
    "9cf333cafbd444739b67a2db58fc71ba":{
      "scriptId":"u11"},
    "c4b55664ede843e6936680a920e58756":{
      "scriptId":"u12"},
    "9432ffb6a22e45b8b95865631dccb203":{
      "scriptId":"u13"},
    "56a65db34ff342ccb8ae27e530c8ab61":{
      "scriptId":"u14"},
    "560914d81a7a4543af2dfdd43db22b45":{
      "scriptId":"u15"},
    "e769545c7d0943089fcdf9eecc71e966":{
      "scriptId":"u16"},
    "72b5d5ac28f2453c8f39ebcae83a1e7a":{
      "scriptId":"u17"},
    "255cd50527bc485db2a6cd35a9fa74e2":{
      "scriptId":"u18"},
    "afc074ad432d4878b08be5192cc4ab7d":{
      "scriptId":"u19"},
    "45d59b0d273342a1bc9f7e86b520e762":{
      "scriptId":"u20"},
    "5df5b1d8f0f74f2fa85bae03bc1b7a8b":{
      "scriptId":"u21"},
    "44c49aaff9e6466aa78db311d0659e5e":{
      "scriptId":"u22"},
    "206e6e34037548dd816da6672708601a":{
      "scriptId":"u23"},
    "7897f867b0be4b16a2662bed64233e1f":{
      "scriptId":"u24"},
    "7af1d4d7676145cbae9de891e10f2c92":{
      "scriptId":"u25"},
    "c4ed9846ed654f0aabb3613ca5c6cac4":{
      "scriptId":"u26"},
    "7011623e291a4b258a101eacb4caf49e":{
      "scriptId":"u27"},
    "f53a50524d98464f97f8091f3cf7d91b":{
      "scriptId":"u28"},
    "d1c8e25d183f467ca3adff2c266eb268":{
      "scriptId":"u29"},
    "a432309935014f4cb9457deb4f342830":{
      "scriptId":"u30"},
    "af45aa9f3d194971a35798238c5355b2":{
      "scriptId":"u31"},
    "3538d8af73de47a2bb72b8fcbd1ea293":{
      "scriptId":"u32"},
    "b8c23b3ac09d4c98a104dd40db925f51":{
      "scriptId":"u33"},
    "517934cdff8744b789911507b0ec86f2":{
      "scriptId":"u34"},
    "fe6ae50aabd940baa67222566f88880d":{
      "scriptId":"u35"},
    "dfb3610fb7e24943b90d37dba2250af9":{
      "scriptId":"u36"},
    "720d3198a8f24d5b9723db6e9a0f75e6":{
      "scriptId":"u37"},
    "164f1bab0dd84c3cb2c41683ef21d099":{
      "scriptId":"u38"},
    "112e1778f3b64ce8b3ebe1eb84182e35":{
      "scriptId":"u39"},
    "e6832a59e2ce4332ad76eab66c1c33f1":{
      "scriptId":"u40"},
    "8298d83b51f9431587d6fe0f3bf26c48":{
      "scriptId":"u41"}}});