$axure.loadCurrentPage({
  "url":"企业入口.html",
  "generationDate":new Date(1490338075416.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f189fcae2baf4874abde843e78124236",
    "type":"Axure:Page",
    "name":"企业入口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90f4dcc124e34b47838b1f0e5695ee8d",
          "label":"1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF66,
                  "opacity":1}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF6699FF},
{
                  "color":0xFF789BC3},
{
                  "color":0xFF789BC3}]},
            "size":{
              "width":1840,
              "height":3880},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9AB4D5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07679fa438934ed2953ebb6cc041d826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF66,
                      "opacity":1}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF6699FF},
{
                      "color":0xFF789BC3},
{
                      "color":0xFF789BC3}]},
                "size":{
                  "width":1840,
                  "height":3880},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9AB4D5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/1_u0.png",
            "selected~":"images/核心产品/1_u0.png"}},
{
          "id":"0c6154fdfef04457b308f60928112c41",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":25},
            "size":{
              "width":60,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bfe5dd456eb40b3b0f53c9a858b02a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":25},
                "size":{
                  "width":60,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u59.png"}},
{
          "id":"c516df191d4643a38ab33eacff1a53a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":170,
              "y":36},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd928cee723a4577973a9884a181406d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":36},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"全心全意，联心共赢！PS：注意不要用方正字体"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69cd1f3d710148c9bd1eb69d0924315d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":775,
              "y":42},
            "size":{
              "width":46,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e43c79fa3a3449cb36d59347736b344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":775,
                  "y":42},
                "size":{
                  "width":46,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"af47a0e9b093467fad19344028e2a5db",
          "label":"erjicaidan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":842.5,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"fde906d8816c4a16a4453d1c3f743001",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fe85e1d4b6264662895486c5069192f6",
                  "label":"erjicaidan",
                  "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC},
                    "size":{
                      "width":160,
                      "height":290},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"209583c2b4ef40839354742fbeb2abb9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC},
                        "size":{
                          "width":160,
                          "height":290},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/erjicaidan_u9.png"}},
{
                  "id":"9c054da3eef74263998b30c7141c2708",
                  "label":"",
                  "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":121},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00556d38a3f244988b26856cc8a9096f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":121},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"1ede0d9607434df091b85a886f64e1c7",
                  "label":"",
                  "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":153},
                    "size":{
                      "width":38,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec2a77128dfb4f28991d68c52dba4474",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":153},
                        "size":{
                          "width":38,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["fe85e1d4b6264662895486c5069192f6"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"b67e6a5f16f4483989b4d04917d7d75a",
                  "label":"",
                  "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":185},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce07cb638c4240c0a528b426c99ba24c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":185},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["fe85e1d4b6264662895486c5069192f6"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"cb6b9010b1574bc6825dace7b4448dc0",
                  "label":"",
                  "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":217},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ef63c3f6c0446b084baed5a55521605",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":217},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["fe85e1d4b6264662895486c5069192f6"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"b4bbfca6b56a4f3c9c34d2d0413e008a",
                  "label":"",
                  "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":249},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"615ba24e670b498396d50ca073a93a63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af47a0e9b093467fad19344028e2a5db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":249},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["fe85e1d4b6264662895486c5069192f6"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"6a31ec35a299430b9318a1da22448ddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":877,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00214a0f687b4bf28e2a99508ff73344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":877,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["af47a0e9b093467fad19344028e2a5db"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["af47a0e9b093467fad19344028e2a5db"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"32be965fa0e844e587993b1821051df4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1023,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf72bd0b4394401883ef57f62ba6407a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1023,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务咨询",
                      "target":{
                        "targetType":"page",
                        "url":"服务咨询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"417ed5dd045c45e99bad1ba2cca62d23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1170,
              "y":42},
            "size":{
              "width":113,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed77916dac9946c0bdb56713337debbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1170,
                  "y":42},
                "size":{
                  "width":113,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"677e5acf4eed4714919150ab828d3dc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1339,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b198e5ba58ce40779e776ad0f4162e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1339,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"bbadae0a243c4f548ba753f59c5b1e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1485,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7ce67ade2e446619c8495f3fe6591aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1485,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"64daa78a2a1643338d97c0f8dc4779b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF66,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1632,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724ab5ba24ff4a278b709772780ffc1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF66,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1632,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"8c4e4237bd8c491384e89b6508a88e5e",
          "label":"biankuang",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2433b6cbf9947c3bce1e943005eba2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":1840,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/biankuang_u33.png"}},
{
          "id":"b65e5ef0ed384ed689d458eb94a544ca",
          "label":"fengexian",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 2 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["b65e5ef0ed384ed689d458eb94a544ca"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]},
            "onResize":{
              "description":"OnResize",
              "cases":[{
                  "description":"用例 2<br> (If &quot;[[this.width]]&quot; ≥ &quot;1800&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">=",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1800",
                      "stos":[]}},
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 1840 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["b65e5ef0ed384ed689d458eb94a544ca"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1840",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]},
{
                  "description":"用例 1<br> (Else If &quot;[[this.width]]&quot; &lt; &quot;1840&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1840",
                      "stos":[]}},
                  "actions":[{
                      "action":"wait",
                      "description":"等待100毫秒",
                      "waitTime":100},
{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to [[this.width+80]] x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["b65e5ef0ed384ed689d458eb94a544ca"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"[[this.width+80]]",
                              "localVariables":{
},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"binOp",
                                  "op":"+",
                                  "leftSTO":{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"width"},
                                  "rightSTO":{
                                    "computedType":"int",
                                    "sto":"literal",
                                    "value":80}}]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ce59613acaf94b84b20d840ae0583cb0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6fecfbd2e73f4db6853f029918b51fbe",
                  "label":"",
                  "parentDynamicPanel":"b65e5ef0ed384ed689d458eb94a544ca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF3E7865},
{
                          "color":0xFF3E7865},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]},
                    "size":{
                      "width":1840,
                      "height":3},
                    "borderFill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF27AB7E},
{
                          "color":0xFF27AB7E},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"92ca2ec2bd524a1d9f56c827faadb797",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b65e5ef0ed384ed689d458eb94a544ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF3E7865},
{
                              "color":0xFF3E7865},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]},
                        "size":{
                          "width":1840,
                          "height":3},
                        "borderFill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF27AB7E},
{
                              "color":0xFF27AB7E},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u80.png"}},
{
                  "id":"8ce2c6c7c4c94312bfebf03a4842b95d",
                  "label":"",
                  "parentDynamicPanel":"b65e5ef0ed384ed689d458eb94a544ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-448,
                      "y":146},
                    "size":{
                      "width":2298,
                      "height":294}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"508726aea6fb481ba5bcd83aaadd7cd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b65e5ef0ed384ed689d458eb94a544ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-448,
                          "y":146},
                        "size":{
                          "width":2298,
                          "height":294}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/u38.png"}}]}]},
{
          "id":"e793805a9fad4b4792b4e54f3a65dd10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":46},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8646a817db52436785e3243adf344b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":46},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "90f4dcc124e34b47838b1f0e5695ee8d":{
      "scriptId":"u0"},
    "07679fa438934ed2953ebb6cc041d826":{
      "scriptId":"u1"},
    "0c6154fdfef04457b308f60928112c41":{
      "scriptId":"u2"},
    "9bfe5dd456eb40b3b0f53c9a858b02a7":{
      "scriptId":"u3"},
    "c516df191d4643a38ab33eacff1a53a5":{
      "scriptId":"u4"},
    "fd928cee723a4577973a9884a181406d":{
      "scriptId":"u5"},
    "69cd1f3d710148c9bd1eb69d0924315d":{
      "scriptId":"u6"},
    "4e43c79fa3a3449cb36d59347736b344":{
      "scriptId":"u7"},
    "af47a0e9b093467fad19344028e2a5db":{
      "scriptId":"u8"},
    "fe85e1d4b6264662895486c5069192f6":{
      "scriptId":"u9"},
    "209583c2b4ef40839354742fbeb2abb9":{
      "scriptId":"u10"},
    "9c054da3eef74263998b30c7141c2708":{
      "scriptId":"u11"},
    "00556d38a3f244988b26856cc8a9096f":{
      "scriptId":"u12"},
    "1ede0d9607434df091b85a886f64e1c7":{
      "scriptId":"u13"},
    "ec2a77128dfb4f28991d68c52dba4474":{
      "scriptId":"u14"},
    "b67e6a5f16f4483989b4d04917d7d75a":{
      "scriptId":"u15"},
    "ce07cb638c4240c0a528b426c99ba24c":{
      "scriptId":"u16"},
    "cb6b9010b1574bc6825dace7b4448dc0":{
      "scriptId":"u17"},
    "1ef63c3f6c0446b084baed5a55521605":{
      "scriptId":"u18"},
    "b4bbfca6b56a4f3c9c34d2d0413e008a":{
      "scriptId":"u19"},
    "615ba24e670b498396d50ca073a93a63":{
      "scriptId":"u20"},
    "6a31ec35a299430b9318a1da22448ddb":{
      "scriptId":"u21"},
    "00214a0f687b4bf28e2a99508ff73344":{
      "scriptId":"u22"},
    "32be965fa0e844e587993b1821051df4":{
      "scriptId":"u23"},
    "cf72bd0b4394401883ef57f62ba6407a":{
      "scriptId":"u24"},
    "417ed5dd045c45e99bad1ba2cca62d23":{
      "scriptId":"u25"},
    "ed77916dac9946c0bdb56713337debbf":{
      "scriptId":"u26"},
    "677e5acf4eed4714919150ab828d3dc3":{
      "scriptId":"u27"},
    "b198e5ba58ce40779e776ad0f4162e95":{
      "scriptId":"u28"},
    "bbadae0a243c4f548ba753f59c5b1e43":{
      "scriptId":"u29"},
    "f7ce67ade2e446619c8495f3fe6591aa":{
      "scriptId":"u30"},
    "64daa78a2a1643338d97c0f8dc4779b4":{
      "scriptId":"u31"},
    "724ab5ba24ff4a278b709772780ffc1c":{
      "scriptId":"u32"},
    "8c4e4237bd8c491384e89b6508a88e5e":{
      "scriptId":"u33"},
    "e2433b6cbf9947c3bce1e943005eba2a":{
      "scriptId":"u34"},
    "b65e5ef0ed384ed689d458eb94a544ca":{
      "scriptId":"u35"},
    "6fecfbd2e73f4db6853f029918b51fbe":{
      "scriptId":"u36"},
    "92ca2ec2bd524a1d9f56c827faadb797":{
      "scriptId":"u37"},
    "8ce2c6c7c4c94312bfebf03a4842b95d":{
      "scriptId":"u38"},
    "508726aea6fb481ba5bcd83aaadd7cd2":{
      "scriptId":"u39"},
    "e793805a9fad4b4792b4e54f3a65dd10":{
      "scriptId":"u40"},
    "8646a817db52436785e3243adf344b6c":{
      "scriptId":"u41"}}});