$axure.loadCurrentPage({
  "url":"加入全联.html",
  "generationDate":new Date(1490338074713.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4d049fd4c6464dc9bce0e1a0a57bb260",
    "type":"Axure:Page",
    "name":"加入全联",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f1b47c10fbf644fb996876e8f3113621",
          "label":"1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF66,
                  "opacity":1}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF6699FF},
{
                  "color":0xFF789BC3},
{
                  "color":0xFF789BC3}]},
            "size":{
              "width":1840,
              "height":3880},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9AB4D5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc7882e30cd4269ade5fd0a61190aff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF66,
                      "opacity":1}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF6699FF},
{
                      "color":0xFF789BC3},
{
                      "color":0xFF789BC3}]},
                "size":{
                  "width":1840,
                  "height":3880},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9AB4D5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/1_u0.png",
            "selected~":"images/核心产品/1_u0.png"}},
{
          "id":"dbe4039f77414b368dad2a1653914b0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":25},
            "size":{
              "width":60,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ac4f35e6e744fb9b09b52266670292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":25},
                "size":{
                  "width":60,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u59.png"}},
{
          "id":"3e5a396565ac4788ae8920020d77eaa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":170,
              "y":36},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ffde63fc24241e5aab7188f4d4a9e63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":36},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"全心全意，联心共赢！PS：注意不要用方正字体"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19c8352ad59a4bee97c0aa0df8a5cb38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":775,
              "y":42},
            "size":{
              "width":46,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15317f0a00d142638f5704a83742d82f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":775,
                  "y":42},
                "size":{
                  "width":46,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"00f36226a5654fb58e6942c1fe05eca6",
          "label":"erjicaidan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":842.5,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b2016f49647542228149f9add9898d00",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ef78e0de578c4efc933e89a451af0f2b",
                  "label":"erjicaidan",
                  "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC},
                    "size":{
                      "width":160,
                      "height":290},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"803ee09a67cc4be5a34eeb3f9c8b5f2f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC},
                        "size":{
                          "width":160,
                          "height":290},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/erjicaidan_u9.png"}},
{
                  "id":"4f1701ab70c148bab20fb0bd69f8dd75",
                  "label":"",
                  "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":121},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a091f9a1cd1f4e08bcddec243f005fb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":121},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f67b8ec8ac394cbc8646c5404259297a",
                  "label":"",
                  "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":153},
                    "size":{
                      "width":38,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18192c5a41f9492b8eecd2fc565906d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":153},
                        "size":{
                          "width":38,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ef78e0de578c4efc933e89a451af0f2b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"b6d364e436954d1f9e96fde6788f48a1",
                  "label":"",
                  "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":185},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf81b56954894408aab515ac0ed87eef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":185},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ef78e0de578c4efc933e89a451af0f2b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"20848e9abc6c4c1c9a05ed4803e5d98b",
                  "label":"",
                  "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":217},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ec18347eeb446f4a1734e4c54386b27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":217},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ef78e0de578c4efc933e89a451af0f2b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"6e458635780749afa2dec72eb1db8c39",
                  "label":"",
                  "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":249},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa346f389c3b4039b5d142b98dc99d7f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00f36226a5654fb58e6942c1fe05eca6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":249},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["ef78e0de578c4efc933e89a451af0f2b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"13ed7f02433543ca913c9aad03da8b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":877,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a903ae5149949d892148af5a267f26b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":877,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["00f36226a5654fb58e6942c1fe05eca6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["00f36226a5654fb58e6942c1fe05eca6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"ec8c0ffff1bd479b8991c868d57293cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1023,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5f8b7194c9e4bcb8aa4314812845d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1023,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务咨询",
                      "target":{
                        "targetType":"page",
                        "url":"服务咨询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"debc62d58e1f48c78b3dbdbbd9d2ca64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1170,
              "y":42},
            "size":{
              "width":113,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf1b5570c08b406f8a0964a91b69385a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1170,
                  "y":42},
                "size":{
                  "width":113,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a07602c3c02049ba80f3863416f638f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1339,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1215066cce24546bf1f3e9e173896ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1339,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f1e6abc58f324f57ba5893e4a2b1c165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1485,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9c0f7ea54bb49f08b7d350dcb7c923f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1485,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"05834f106a064e2f94f04a3cdd9e8ba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF66,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1632,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940ce45025464f3cbdb7d8e70086a945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF66,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1632,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c56c31e84d0148fa8b93da8d0e21e7b4",
          "label":"biankuang",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49c6b57b3f0045f898ab4287cfca3dc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":1840,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/biankuang_u33.png"}},
{
          "id":"ce67faa0d01f4cc2b3dae073a5ad412c",
          "label":"fengexian",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 2 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["ce67faa0d01f4cc2b3dae073a5ad412c"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]},
            "onResize":{
              "description":"OnResize",
              "cases":[{
                  "description":"用例 2<br> (If &quot;[[this.width]]&quot; ≥ &quot;1800&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">=",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1800",
                      "stos":[]}},
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 1840 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["ce67faa0d01f4cc2b3dae073a5ad412c"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1840",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]},
{
                  "description":"用例 1<br> (Else If &quot;[[this.width]]&quot; &lt; &quot;1840&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1840",
                      "stos":[]}},
                  "actions":[{
                      "action":"wait",
                      "description":"等待100毫秒",
                      "waitTime":100},
{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to [[this.width+80]] x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["ce67faa0d01f4cc2b3dae073a5ad412c"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"[[this.width+80]]",
                              "localVariables":{
},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"binOp",
                                  "op":"+",
                                  "leftSTO":{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"width"},
                                  "rightSTO":{
                                    "computedType":"int",
                                    "sto":"literal",
                                    "value":80}}]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0b14813bf39b4fd38e150e647406f1b7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1fcfdc837e8146ee9a6bb4b50bd6774d",
                  "label":"",
                  "parentDynamicPanel":"ce67faa0d01f4cc2b3dae073a5ad412c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF3E7865},
{
                          "color":0xFF3E7865},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]},
                    "size":{
                      "width":1840,
                      "height":3},
                    "borderFill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF27AB7E},
{
                          "color":0xFF27AB7E},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"932835a8a2124d0483b9ac2217b08e4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce67faa0d01f4cc2b3dae073a5ad412c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF3E7865},
{
                              "color":0xFF3E7865},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]},
                        "size":{
                          "width":1840,
                          "height":3},
                        "borderFill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF27AB7E},
{
                              "color":0xFF27AB7E},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u80.png"}},
{
                  "id":"360eb6889d8f45e2841acf9fb671b7c0",
                  "label":"",
                  "parentDynamicPanel":"ce67faa0d01f4cc2b3dae073a5ad412c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-448,
                      "y":146},
                    "size":{
                      "width":2298,
                      "height":294}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c412ac7b3aa1468cb1cf9eacc832f99e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce67faa0d01f4cc2b3dae073a5ad412c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-448,
                          "y":146},
                        "size":{
                          "width":2298,
                          "height":294}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/u38.png"}}]}]},
{
          "id":"e5bea72f4b1a45fdb46e801a112a52db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":46},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb79945255364335a69376c1f3ffb052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":46},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f1b47c10fbf644fb996876e8f3113621":{
      "scriptId":"u0"},
    "3cc7882e30cd4269ade5fd0a61190aff":{
      "scriptId":"u1"},
    "dbe4039f77414b368dad2a1653914b0b":{
      "scriptId":"u2"},
    "d1ac4f35e6e744fb9b09b52266670292":{
      "scriptId":"u3"},
    "3e5a396565ac4788ae8920020d77eaa1":{
      "scriptId":"u4"},
    "9ffde63fc24241e5aab7188f4d4a9e63":{
      "scriptId":"u5"},
    "19c8352ad59a4bee97c0aa0df8a5cb38":{
      "scriptId":"u6"},
    "15317f0a00d142638f5704a83742d82f":{
      "scriptId":"u7"},
    "00f36226a5654fb58e6942c1fe05eca6":{
      "scriptId":"u8"},
    "ef78e0de578c4efc933e89a451af0f2b":{
      "scriptId":"u9"},
    "803ee09a67cc4be5a34eeb3f9c8b5f2f":{
      "scriptId":"u10"},
    "4f1701ab70c148bab20fb0bd69f8dd75":{
      "scriptId":"u11"},
    "a091f9a1cd1f4e08bcddec243f005fb7":{
      "scriptId":"u12"},
    "f67b8ec8ac394cbc8646c5404259297a":{
      "scriptId":"u13"},
    "18192c5a41f9492b8eecd2fc565906d3":{
      "scriptId":"u14"},
    "b6d364e436954d1f9e96fde6788f48a1":{
      "scriptId":"u15"},
    "cf81b56954894408aab515ac0ed87eef":{
      "scriptId":"u16"},
    "20848e9abc6c4c1c9a05ed4803e5d98b":{
      "scriptId":"u17"},
    "0ec18347eeb446f4a1734e4c54386b27":{
      "scriptId":"u18"},
    "6e458635780749afa2dec72eb1db8c39":{
      "scriptId":"u19"},
    "aa346f389c3b4039b5d142b98dc99d7f":{
      "scriptId":"u20"},
    "13ed7f02433543ca913c9aad03da8b2d":{
      "scriptId":"u21"},
    "9a903ae5149949d892148af5a267f26b":{
      "scriptId":"u22"},
    "ec8c0ffff1bd479b8991c868d57293cc":{
      "scriptId":"u23"},
    "b5f8b7194c9e4bcb8aa4314812845d36":{
      "scriptId":"u24"},
    "debc62d58e1f48c78b3dbdbbd9d2ca64":{
      "scriptId":"u25"},
    "cf1b5570c08b406f8a0964a91b69385a":{
      "scriptId":"u26"},
    "a07602c3c02049ba80f3863416f638f8":{
      "scriptId":"u27"},
    "d1215066cce24546bf1f3e9e173896ba":{
      "scriptId":"u28"},
    "f1e6abc58f324f57ba5893e4a2b1c165":{
      "scriptId":"u29"},
    "f9c0f7ea54bb49f08b7d350dcb7c923f":{
      "scriptId":"u30"},
    "05834f106a064e2f94f04a3cdd9e8ba8":{
      "scriptId":"u31"},
    "940ce45025464f3cbdb7d8e70086a945":{
      "scriptId":"u32"},
    "c56c31e84d0148fa8b93da8d0e21e7b4":{
      "scriptId":"u33"},
    "49c6b57b3f0045f898ab4287cfca3dc2":{
      "scriptId":"u34"},
    "ce67faa0d01f4cc2b3dae073a5ad412c":{
      "scriptId":"u35"},
    "1fcfdc837e8146ee9a6bb4b50bd6774d":{
      "scriptId":"u36"},
    "932835a8a2124d0483b9ac2217b08e4b":{
      "scriptId":"u37"},
    "360eb6889d8f45e2841acf9fb671b7c0":{
      "scriptId":"u38"},
    "c412ac7b3aa1468cb1cf9eacc832f99e":{
      "scriptId":"u39"},
    "e5bea72f4b1a45fdb46e801a112a52db":{
      "scriptId":"u40"},
    "bb79945255364335a69376c1f3ffb052":{
      "scriptId":"u41"}}});