$axure.loadCurrentPage({
  "url":"合作与生态.html",
  "generationDate":new Date(1490338072542.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8892f6e5b40401a87d730204003832c",
    "type":"Axure:Page",
    "name":"合作与生态",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6276979a0f7d499b84db422fe17b1baa",
          "label":"1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF66,
                  "opacity":1}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF9FB8D4},
{
                  "color":0xFF6699FF},
{
                  "color":0xFF789BC3},
{
                  "color":0xFF789BC3}]},
            "size":{
              "width":1840,
              "height":1230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9AB4D5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1520134950af4ba19b0824faaea94364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF66,
                      "opacity":1}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF9FB8D4},
{
                      "color":0xFF6699FF},
{
                      "color":0xFF789BC3},
{
                      "color":0xFF789BC3}]},
                "size":{
                  "width":1840,
                  "height":1230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9AB4D5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合作与生态/1_u0.png",
            "selected~":"images/合作与生态/1_u0.png"}},
{
          "id":"bcaa278db90b43bd92f6758457b1feb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":25},
            "size":{
              "width":60,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34bcba91beaf407bb6670402b6792c84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":25},
                "size":{
                  "width":60,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u59.png"}},
{
          "id":"35f0124052dc4e9998d6e97cb8967737",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":170,
              "y":36},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7a459987c241eb9a84c54fdb892480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":36},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"全心全意，联心共赢！PS：注意不要用方正字体"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc5d5a52ff54e3eb7b9769f69a907bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":775,
              "y":42},
            "size":{
              "width":46,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5995e61b5e8e4b56a0032c32f9a4f4b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":775,
                  "y":42},
                "size":{
                  "width":46,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c424d25c60ee41418bbddf7dba1b5245",
          "label":"erjicaidan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":842.5,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"33ff5475e28541278ca30e1b0b2a459e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6b70280f24844af2bebd08fe947b0f7b",
                  "label":"erjicaidan",
                  "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC},
                    "size":{
                      "width":160,
                      "height":290},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3566f8a4a3c34b419119571cbb82d5d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC},
                        "size":{
                          "width":160,
                          "height":290},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/erjicaidan_u9.png"}},
{
                  "id":"5b7148e8b6794b9a97aaa10ea1269bca",
                  "label":"",
                  "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":121},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e79f004311fb4ff2a40ca028bc288eb2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":121},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"2713a6e6c8044b6d9e1ac1ef71bd65d2",
                  "label":"",
                  "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":153},
                    "size":{
                      "width":38,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ce28d3a3db9482bafcc5f23d2308ead",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":153},
                        "size":{
                          "width":38,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["6b70280f24844af2bebd08fe947b0f7b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"2f4aeacd6bc747a68916e44ca76c1d7e",
                  "label":"",
                  "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":185},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d52eb510cf04bdaa6b95ba7998d6f7f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":185},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["6b70280f24844af2bebd08fe947b0f7b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"ea43f819f814485e818e682094e2b73e",
                  "label":"",
                  "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":217},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a3a94df59664fd083be0140f2f33350",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":217},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["6b70280f24844af2bebd08fe947b0f7b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"a94cb7a767a14bd185b18c91202599d4",
                  "label":"",
                  "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1}}},
                    "location":{
                      "x":40,
                      "y":249},
                    "size":{
                      "width":75,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e276bfb87bd04098b1ce8d76d72c708d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c424d25c60ee41418bbddf7dba1b5245",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1}}},
                        "location":{
                          "x":40,
                          "y":249},
                        "size":{
                          "width":75,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 This = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 erjicaidan",
                              "objectsToFades":[{
                                  "objectPath":["6b70280f24844af2bebd08fe947b0f7b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"a4d6aee00b8d4cf992e959b4091a19ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":877,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d9e99b3bd164e2a9081c3b4fa76fdc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":877,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["c424d25c60ee41418bbddf7dba1b5245"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 erjicaidan",
                      "objectsToFades":[{
                          "objectPath":["c424d25c60ee41418bbddf7dba1b5245"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7cd263b9d37542b59a331d51649ff213",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1023,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15fcfbe988e44c55b01d38b909d55cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1023,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务咨询",
                      "target":{
                        "targetType":"page",
                        "url":"服务咨询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6ba7043c17594030bd989df8bd5be570",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1170,
              "y":42},
            "size":{
              "width":113,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d522cc0ff364e3c8c2976146ae18d64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1170,
                  "y":42},
                "size":{
                  "width":113,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 合作与生态",
                      "target":{
                        "targetType":"page",
                        "url":"合作与生态.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a5a8e0b44e764bfa87b1b30d21669047",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1339,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8948e32160c44b1d8c916b21dd6d4b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1339,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"8f6a3f4f68dd431ba3893c8695c61326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1485,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c3eef5851d4cae9d88d557b70c90c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1485,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"e022f675b6864bfba09194a2a98479fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF66,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1632,
              "y":42},
            "size":{
              "width":91,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd8d28adb6904ddeac37818c262269bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF66,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1632,
                  "y":42},
                "size":{
                  "width":91,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"30832f04bf644dd9a9c439021e29235e",
          "label":"biankuang",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"481bb28bb6f64c24b1b858940bfa0f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":1840,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/biankuang_u33.png"}},
{
          "id":"f7c6e397bda3494f90bc7ce08e88e8c6",
          "label":"fengexian",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":1840,
              "height":3}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 2 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["f7c6e397bda3494f90bc7ce08e88e8c6"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]},
            "onResize":{
              "description":"OnResize",
              "cases":[{
                  "description":"用例 2<br> (If &quot;[[this.width]]&quot; ≥ &quot;1800&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">=",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1800",
                      "stos":[]}},
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to 1840 x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["f7c6e397bda3494f90bc7ce08e88e8c6"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1840",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]},
{
                  "description":"用例 1<br> (Else If &quot;[[this.width]]&quot; &lt; &quot;1840&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.width]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"width"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1840",
                      "stos":[]}},
                  "actions":[{
                      "action":"wait",
                      "description":"等待100毫秒",
                      "waitTime":100},
{
                      "action":"setWidgetSize",
                      "description":"设置动态面板 fengexian to [[this.width+80]] x 5 大小",
                      "objectsToResize":[{
                          "objectPath":["f7c6e397bda3494f90bc7ce08e88e8c6"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"[[this.width+80]]",
                              "localVariables":{
},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"binOp",
                                  "op":"+",
                                  "leftSTO":{
                                    "computedType":"int",
                                    "sto":"propCall",
                                    "thisSTO":{
                                      "sto":"var",
                                      "name":"this"},
                                    "prop":"width"},
                                  "rightSTO":{
                                    "computedType":"int",
                                    "sto":"literal",
                                    "value":80}}]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"5",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"37eea660adc145179801aadd63b8faeb",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0d818f9cf04c4eff8d2ab91a504f277c",
                  "label":"",
                  "parentDynamicPanel":"f7c6e397bda3494f90bc7ce08e88e8c6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF3E7865},
{
                          "color":0xFF3E7865},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]},
                    "size":{
                      "width":1840,
                      "height":3},
                    "borderFill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF27AB7E},
{
                          "color":0xFF27AB7E},
{
                          "color":0xFF02BB7C},
{
                          "color":0xFF00D58C},
{
                          "color":0xFF00D58C}]}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"500e0782172e485dbbefb2f5cb3ccd9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7c6e397bda3494f90bc7ce08e88e8c6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF3E7865},
{
                              "color":0xFF3E7865},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]},
                        "size":{
                          "width":1840,
                          "height":3},
                        "borderFill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF27AB7E},
{
                              "color":0xFF27AB7E},
{
                              "color":0xFF02BB7C},
{
                              "color":0xFF00D58C},
{
                              "color":0xFF00D58C}]}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u80.png"}},
{
                  "id":"dcb7624d12fb4d9b9aeef636e2f913d3",
                  "label":"",
                  "parentDynamicPanel":"f7c6e397bda3494f90bc7ce08e88e8c6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-448,
                      "y":146},
                    "size":{
                      "width":2298,
                      "height":294}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31a8e345c4e2421691bfc8ef6a500ebb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7c6e397bda3494f90bc7ce08e88e8c6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-448,
                          "y":146},
                        "size":{
                          "width":2298,
                          "height":294}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/核心产品/u38.png"}}]}]},
{
          "id":"384b6fc7ea624236b2157e1ed9e3b29f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":46},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb6e2d5d777040769dc8d1953240f544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":46},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核心产品/u40.png"}},
{
          "id":"1e63e68d933e4a3ca4349a9bc74b72db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":140},
            "size":{
              "width":133,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2707e914ca3424cb82d516cf2c26cfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":140},
                "size":{
                  "width":133,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"865679be4ac6499fb3add9e57b2be4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":193},
            "size":{
              "width":188,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c95b52d19cdc4ad89d984ba6c63a43a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":193},
                "size":{
                  "width":188,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6276979a0f7d499b84db422fe17b1baa":{
      "scriptId":"u0"},
    "1520134950af4ba19b0824faaea94364":{
      "scriptId":"u1"},
    "bcaa278db90b43bd92f6758457b1feb9":{
      "scriptId":"u2"},
    "34bcba91beaf407bb6670402b6792c84":{
      "scriptId":"u3"},
    "35f0124052dc4e9998d6e97cb8967737":{
      "scriptId":"u4"},
    "0a7a459987c241eb9a84c54fdb892480":{
      "scriptId":"u5"},
    "7dc5d5a52ff54e3eb7b9769f69a907bf":{
      "scriptId":"u6"},
    "5995e61b5e8e4b56a0032c32f9a4f4b5":{
      "scriptId":"u7"},
    "c424d25c60ee41418bbddf7dba1b5245":{
      "scriptId":"u8"},
    "6b70280f24844af2bebd08fe947b0f7b":{
      "scriptId":"u9"},
    "3566f8a4a3c34b419119571cbb82d5d3":{
      "scriptId":"u10"},
    "5b7148e8b6794b9a97aaa10ea1269bca":{
      "scriptId":"u11"},
    "e79f004311fb4ff2a40ca028bc288eb2":{
      "scriptId":"u12"},
    "2713a6e6c8044b6d9e1ac1ef71bd65d2":{
      "scriptId":"u13"},
    "1ce28d3a3db9482bafcc5f23d2308ead":{
      "scriptId":"u14"},
    "2f4aeacd6bc747a68916e44ca76c1d7e":{
      "scriptId":"u15"},
    "5d52eb510cf04bdaa6b95ba7998d6f7f":{
      "scriptId":"u16"},
    "ea43f819f814485e818e682094e2b73e":{
      "scriptId":"u17"},
    "0a3a94df59664fd083be0140f2f33350":{
      "scriptId":"u18"},
    "a94cb7a767a14bd185b18c91202599d4":{
      "scriptId":"u19"},
    "e276bfb87bd04098b1ce8d76d72c708d":{
      "scriptId":"u20"},
    "a4d6aee00b8d4cf992e959b4091a19ef":{
      "scriptId":"u21"},
    "6d9e99b3bd164e2a9081c3b4fa76fdc2":{
      "scriptId":"u22"},
    "7cd263b9d37542b59a331d51649ff213":{
      "scriptId":"u23"},
    "15fcfbe988e44c55b01d38b909d55cc2":{
      "scriptId":"u24"},
    "6ba7043c17594030bd989df8bd5be570":{
      "scriptId":"u25"},
    "1d522cc0ff364e3c8c2976146ae18d64":{
      "scriptId":"u26"},
    "a5a8e0b44e764bfa87b1b30d21669047":{
      "scriptId":"u27"},
    "8948e32160c44b1d8c916b21dd6d4b3f":{
      "scriptId":"u28"},
    "8f6a3f4f68dd431ba3893c8695c61326":{
      "scriptId":"u29"},
    "b7c3eef5851d4cae9d88d557b70c90c8":{
      "scriptId":"u30"},
    "e022f675b6864bfba09194a2a98479fd":{
      "scriptId":"u31"},
    "bd8d28adb6904ddeac37818c262269bb":{
      "scriptId":"u32"},
    "30832f04bf644dd9a9c439021e29235e":{
      "scriptId":"u33"},
    "481bb28bb6f64c24b1b858940bfa0f2a":{
      "scriptId":"u34"},
    "f7c6e397bda3494f90bc7ce08e88e8c6":{
      "scriptId":"u35"},
    "0d818f9cf04c4eff8d2ab91a504f277c":{
      "scriptId":"u36"},
    "500e0782172e485dbbefb2f5cb3ccd9a":{
      "scriptId":"u37"},
    "dcb7624d12fb4d9b9aeef636e2f913d3":{
      "scriptId":"u38"},
    "31a8e345c4e2421691bfc8ef6a500ebb":{
      "scriptId":"u39"},
    "384b6fc7ea624236b2157e1ed9e3b29f":{
      "scriptId":"u40"},
    "cb6e2d5d777040769dc8d1953240f544":{
      "scriptId":"u41"},
    "1e63e68d933e4a3ca4349a9bc74b72db":{
      "scriptId":"u42"},
    "f2707e914ca3424cb82d516cf2c26cfa":{
      "scriptId":"u43"},
    "865679be4ac6499fb3add9e57b2be4e8":{
      "scriptId":"u44"},
    "c95b52d19cdc4ad89d984ba6c63a43a2":{
      "scriptId":"u45"}}});